name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    # This prevents the "run not stop" issue by killing it after 5 minutes
    timeout-minutes: 5 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compile C++ project
      # -static packs libraries into the exe so it runs anywhere
      run: g++ Project.cpp -static -o app.exe

    - name: Run program
      shell: cmd
      run: app.exe
