name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compile C++ project
      # We compile Project.cpp and name the output 'app'
      run: g++ Project.cpp -o app

    - name: Run program
      # This runs the compiled program to make sure it works
      run: ./app
