name: Deploy Web App
on:
  push:
    branches: [ "main" ]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v14
    - name: Compile
      # ASYNCIFY is required to handle the 'cin' input in a browser
      run: emcc Project.cpp -o index.html -s ASYNCIFY
    - name: Upload
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: actions/deploy-pages@v4
